<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8">
<style>
table {
      border-collapse: collapse;
      width: 80%;
}

th {
      padding: 12px;
      text-align: left;
      border-top: 3px solid #ddd;
      border-bottom: 3px solid #ddd;
      font-size: 18px;
}
td {
      padding: 12px;
      text-align: left;
      border-bottom: 3px solid #ddd;
}
</style>
</head>
</head>

<body>
<h1>TTS: </h1>



<h2>Abstract</h2>
<p align="justify" style="font-size:20px">
We work to create a speech synthesis system which can generate
speech with specified style and timbre in a multi-lingual scene.
However, limited existence of polyglot datasets makes multi-
lingual systems hard to generate speech with native pronuncia-
tion. 
</p>
<h3> </h3>


<h2>System Evaluation</h2>
<ul>
<li style="font-size:20px"> <th>Para</th>: Parallel tacotron </li>
<li style="font-size:20px"> <th>M3</th>: A multi-speaker multi-style multi-language speech synthesis baseline system </li>
<li style="font-size:20px"> <th>Ours</th>: Proposed system, which based on Hubert and style
adaptor. </li>

</ul>
<h3> </h3>

<h3> CN </h3>
<table><tr>
<th>Text</th>
<th>Aunque hay turistas, no suele estar muy concurrido.</th>
<th>Los proyectiles no les llegan, utilizan una capa electromagnética.</th>
<th>Aprenderás muchas cosas interesantes mientras te diviertes.</th>
</tr>

<tr>
<th>Para</th>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/ShortSentence/00003.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/ShortSentence/00028.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/ShortSentence/00006.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>M3</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/ShortSentence/00003.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/ShortSentence/00028.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/ShortSentence/00006.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>Ours</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/ShortSentence/00003.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/ShortSentence/00028.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/ShortSentence/00006.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

</table>

<h2>Huber Analysis</h2>

<h3> Voice conversion </h3>
<table><tr>
<th>Text</th>
<th>No tienen miedo de nada, y en algunas ocasiones hasta buscan la confrontación porque esto los estimula.</th>
<th>La memoria es una construcción propia que se alimenta del recuerdo y del olvido.</th>
<th>Compramos unas entradas que decían ser visibilidad reducida, pero era visibilidad cero.</th>
</tr>

<tr>
<th>M2M</th>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>F2M</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>F2F</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>M2M</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

</table>

<h3> Bottleneck Feature Comparison </h3>
<table><tr>
<th>Text</th>
<th>No tienen miedo de nada, y en algunas ocasiones hasta buscan la confrontación porque esto los estimula.</th>
<th>La memoria es una construcción propia que se alimenta del recuerdo y del olvido.</th>
<th>Compramos unas entradas que decían ser visibilidad reducida, pero era visibilidad cero.</th>
</tr>

<tr>
<th>Hubert</th>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>XLSR53-12th</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>ASRE</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>w/o-BNF</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

</table>

<h3> Cross-lingual Style Transfer </h3>
<table><tr>
<th>Text</th>
<th>No tienen miedo de nada, y en algunas ocasiones hasta buscan la confrontación porque esto los estimula.</th>
<th>La memoria es una construcción propia que se alimenta del recuerdo y del olvido.</th>
<th>Compramos unas entradas que decían ser visibilidad reducida, pero era visibilidad cero.</th>
</tr>

<tr>
<th>w/o-Accent-MI</th>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/NonTTS/RECORDING/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

<tr>
<th>Ours</th>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00029.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00013.wav" controls="controls">Audio Tag not supported.</audio></td>
<td><audio src="./audio/bc2021/TTS/NEW/Waves/LongSentence/00016.wav" controls="controls">Audio Tag not supported.</audio></td>
</tr>

</table>

<br>
<br>
<br>
<br>
</body>
</html>


